### ISSUE TITLE
HungryGeese environment, too many open files in Ubuntu 18.04

### ISSUE THREAD

**Issue by natravedrova** [DeNA/HandyRL#102]
Could you please advise on the `Too many open files` error I got when running training? 
Error messages that relate to the code:
```
File "/home/HandyRL/handyrl/worker.py", line 84, in open_worker
worker.run()
File "/home/HandyRL/handyrl/worker.py", line 64, in run
model_pool = self._gather_models(model_ids)
File "/home/HandyRL/handyrl/worker.py", line 50, in _gather_models
model_pool[model_id] = send_recv(self.conn, ('model', model_id))
 File "/home/HandyRL/handyrl/connection.py", line 17, in send_recv
 rdata = conn.recv()
```
config.yaml:
```
env_args:
    env: 'HungryGeese'
    source: 'handyrl.envs.kaggle.hungry_geese'

train_args:
    turn_based_training: True
    observation: False
    gamma: 0.8
    forward_steps: 16
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 200
    batch_size: 128
    minimum_episodes: 400
    maximum_episodes: 100000
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 4
    lambda: 0.7
    policy_target: 'TD' # 'UGPO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    seed: 42
    restart_epoch: 0


worker_args:
    server_address: ''
    num_parallel: 4
```
One GPU (GeForce RTX 2080 Ti).
CUDA Version: 11.0
Anaconda environment with Python 3.7.9
Ubuntu 18.04

**Comment by ikki407** [comment]
Thank you for reporting. Please check your max open file limit in Ubuntu.
```
ulimit -n
```
If the output is 1024 or around it, you need to increase open file limit as below:
```
ulimit -n 65536
```

We have a plan to set automatically when running training/evaluation in `main.py`.
Could you try this?
Thanks

**Comment by ikki407** [comment]
Additionally, we recommend to set environment variable of OpenMP if you use GPUs or train remotely.
This variable limits the inference of pytorch model to 1 CPU. This probably enables the training more efficient.
```
export OMP_NUM_THREADS=1
```

**Comment by natravedrova** [comment]
Thank you @ikki407!
I changed the ulimit, and it looks like the training runs smoothly now.

**Comment by ikki407** [comment]
@natravedrova 
Great! Please ask if anything happens again.
Enjoy RL!
