### ISSUE TITLE
Examples of config.yaml for supported games

### ISSUE THREAD

**Issue by natravedrova** [DeNA/HandyRL#113]
Would you mind sharing sample settings for all games supported by your excellent framework? 

There is `config.yaml` for TicTacToe already. It would be great to have similar files for other games (`config.geister.yaml`, `config.geese.yaml` or commented section in the existing config). I am not sure who are your target audience, but as a newcomer, not all parameters might be obvious.
Any comments in the files would be much appreciated as well.

**Comment by ikki407** [comment]
Thank you for your suggestion and your trial. I agree your advice about target audience.
We are talking about preparing the configs for each game.
And we're planning to describe the parameters and the features of HandyRL in README.
e.g.
- What is `forward_steps ` parameter?
- HandyRL enables policy gradient with off-policy correction, self-play, losses (V-Trace, UPGO)...

What information would make it easier for you and beginners to use?

Please wait for a while...
Thanks

**Comment by natravedrova** [comment]
> What information would make it easier for you and beginners to use?

Thank you @ikki407!  Your plan described in the comment look great.

**Comment by ikki407** [comment]
New PR for parameters. I added more details for training.
https://github.com/DeNA/HandyRL/pull/117

**Comment by ikki407** [comment]
@natravedrova 
I added the parameter descriptions https://github.com/DeNA/HandyRL/blob/master/docs/parameters.md.
Can you see that?
Thanks

**Comment by natravedrova** [comment]
> @natravedrova
> I added the parameter descriptions https://github.com/DeNA/HandyRL/blob/master/docs/parameters.md.
> This was merged and the readme updated.
> Can you see that?
> Thanks

This is fantastic! Thank you very much!

**Comment by ikki407** [comment]
This includes a lot of technical terms. So the explanation how to tune or set the parameters might be noted. 
I will do that after some time...

**Comment by ikki407** [comment]
Hi @natravedrova, we shared the parameters used to train a model for hungry geese in Kaggle discussion. Please check it out.
https://www.kaggle.com/c/hungry-geese/discussion/218190

**Comment by natravedrova** [comment]
I am completely satisfied with all the updates related to config.yaml :-)
