### ISSUE TITLE
How to avoid `OSError: [Errno 24] Too many open files`

### ISSUE THREAD

**Issue by fzdy1914** [DeNA/HandyRL#121]
Hi, I tried your code on a Linux server and find out that `OSError: [Errno 24] Too many open files` may occur if there are too many workers.

If someone else also found this error, add the following code somewhere in your code so the error can be avoided.
```
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
```

**Comment by YuriCat** [comment]
Thanks for your report and great suggestion!

We've never tried this before. It looks very nice for the future update.

**Comment by ikki407** [comment]
Hi @fzdy1914 

We have updated model sending procedure and it will avoid PyTorch shared-memory error and `Too many open files` error so far. Plus, we've investigated the shared memory and the number of the file descriptor during model training. The shared memory and file descriptor kept stable (not increased) in the new implementation.
Please try it again! Thanks

**Comment by ikki407** [comment]
Close this PR because #149 is merged into master.
