### ISSUE TITLE
Customize learning rate

### ISSUE THREAD

**Issue by Jogima-cyber** [DeNA/HandyRL#191]
Hello there! I'd like to customize the learning rate in HandyRL but I don't see anywhere where to to it! In imitation learning my model converges well with a LR of 0.000025, so I'd like to set a similar LR in HandyRL.

**Comment by ikki407** [comment]
Thanks! Currently, the learning rate cannot be set in config. If you want to set it in the config, you can change the code like https://github.com/DeNA/HandyRL/pull/176. The learning rate is set [here in train.py](https://github.com/DeNA/HandyRL/blob/master/handyrl/train.py#L318) (you can change here directly).

What do you think that the learning rate should be set in config? 
cc: @YuriCat

**Comment by Jogima-cyber** [comment]
Thank you!

**Comment by YuriCat** [comment]
@Jogima-cyber 
Hi, thank you for your good suggestion!
Learning rate is obviously an important setting.
I'm considering adding `learing_rate` in configration in the next update!
