### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by takemi853** [DeNA/HandyRL#217]
When I run handyRL in colab or Kaggle, I get the following error.
Is there a problem with loading LuxAI's kaggle-environment?

```
  File "/usr/local/lib/python3.7/dist-packages/kaggle_environments/envs/lux_ai_2021/lux_ai_2021.py", line 106, in interpreter
    player1.observation.globalCityIDCount = match_obs_meta["globalCityIDCount"]
TypeError: list indices must be integers or slices, not str
```

**Comment by YuriCat** [comment]
Hi, @takemi853.
Thank you for your report!
If this situation is specific to Lux AI, sorry to say, we have not tried Lux AI environment, therefore we can't help you .
If this problem stems from a lack of HandyRL assumptions about specific problems, please elaborate.

**Comment by YuriCat** [comment]
Since Lux AI competition is already finished, we will close this issue.
