### ISSUE TITLE
How to make model consider immediate reward ?

### ISSUE THREAD

**Issue by glitter2626** [DeNA/HandyRL#275]
I want to use immediate reward from environment to teach my RL model. As described in the document, I implemented "reward" function in "Environment" class. 

However, when I checked loss calculation flow in train.py file, losses['v'] seems only consider value outputted from model and outcome from environment. Also, I found that loss['r'] takes into account the rewards from the environment. 

Does this mean that my model also needs to output a "return" value ?

**Comment by glitter2626** [comment]
@YuriCat Thanks for your clear reply.

I also have another question about [solo training](https://github.com/DeNA/HandyRL/blob/cb4e8850f094687ebb5a668e97a108f049f28412/handyrl/train.py#L57). In self-play, the model always plays with itself. However, when we choose training batch, we only randomly select an agent's episode. Is there some reason why episodes of all agents are not considered in same batch, e.g. stable training ?

**Comment by YuriCat** [comment]
@glitter2626 Could you please try this fix #276 ?

Of course, we can train all the players at the same time, but we had not been carefully checked such cases. Thank you for your pointing out!
Note that the input might be biased if the observations contain the same data.

**Comment by glitter2626** [comment]
@YuriCat  Thanks your fast solution again!

I have this question is because I want to utilize this awesome framework to deal with multi-agents cooperative problem. I revise some loss calculation step described in VDN paper. But my current solution seems exist some bugs. I will try to fix it. 

All in all, just wanted to thank you for your contributions, I learned a lot from you.
